baseURL = "https://5imili.github.io"
title = "Mili's Storys"
theme = "beautifulhugo"
DefaultContentLanguage = "en"
hasCJKLanguage = true
languageCode = "zh-cn"
metaDataFormat = "yaml"
pygmentsUseClasses = false
pygmentCodeFences = true


[Author]
  name = "555iMili"
  website = "https://5imili.github.io"
  email = "frank@linux.com"
  github = "5imili"

[[menu.main]]
    identifier = "Categories"
    name = "Categories"
    weight = 1

[[menu.main]]
    parent = "Categories"
    name = "kubernetes"
    url = "categories/kubernetes"
    weight = 1
    
[[menu.main]]
    parent = "Categories"
    name = "Cloud Native"
    url = "categories/cloud-native"
    weight = 2

[[menu.main]]
    parent = "Categories"
    name = "Microservices"
    url = "categories/microservices"
    weight = 3

[[menu.main]]
    parent = "Categories"
    name = "Devops"
    url = "categories/devops"
    weight = 4

[[menu.main]]
    parent = "Categories"
    name = "Github"
    url = "categories/github"
    weight = 5

[[menu.main]]
    parent = "Categories"
    name = "Serverless"
    url = "categories/serverless"
    weight = 6

[[menu.main]]
    parent = "Categories"
    name = "Code"
    url = "categories/code"
    weight = 7

[[menu.main]]
    parent = "Categories"
    name = "Tags"
    url = "tags"
    weight = 8

[[menu.main]]
    identifier = "Books"
    name = "Books"
    weight = 2

[[menu.main]]
    parent = "Books"
    name = "Cloud Native Go"
    url = "cloud-native-go"
    weight = 1

[[menu.main]]
    parent = "Books"
    name = "Cloud Native Python"
    url = "posts/cloud-native-python"
    weight = 2

[[menu.main]]
    parent = "Books"
    name = "Kubernetes handbook"
    url = "kubernetes-handbook"
    weight = 3

[[menu.main]]
    parent = "Books"
    name = "Docker handbook"
    url = "docker-handbook"
    weight = 4

[[menu.main]]
    parent = "Books"
    name = "Hugo Handbook"
    url = "hugo-handbook"
    weight = 5

[[menu.main]]
    parent = "Books"
    name = "Istio service mesh"
    url = "http://istio.doczh.cn"
    weight = 6

[[menu.main]]
    parent = "Books"
    name = "Migrating to Cloud Native"
    url = "migrating-to-cloud-native-application-architectures"
    weight = 7

[[menu.main]]
    identifier = "Projects"
    name = "Projects"
    weight = 3

[[menu.main]]
    parent = "Projects"
    name = "Spark on kubernetes"
    url = "spark-on-k8s"
    weight = 1

[[menu.main]]
    parent = "Projects"
    name = "Awesome Cloud Native"
    url = "awesome-cloud-native"
    weight = 2

[[menu.main]]
    parent = "Projects"
    name = "Cloudinary go"
    url = "posts/cloudinary-go"
    weight = 3

[[menu.main]]
    parent = "Projects"
    name = "Magpie"
    url = "posts/yarn-on-docker"
    weight = 4

[[menu.main]]
    parent = "Projects"
    name = "Cheatsheets"
    url = "cheatsheets"
    weight = 5

[[menu.main]]
    name = "About"
    url = "about"
    weight = 4
